version: '3.7'

services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./traefik:/etc/traefik:Z
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --logLevel=DEBUG
      - --entrypoints=Name:http Address::80
      - --defaultentrypoints=http
      - --api.dashboard=true
      - --docker
      - --docker.watch
      - --docker.exposedbydefault=false
      - --docker.domain=localhost

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=HostRegexp:localhost,{subdomain:[a-z]+}.localhost
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    command: nginx-debug -g 'daemon off;'

  front:
    image: emilevauge/whoami
    container_name: front
    restart: unless-stopped

  api:
    image: emilevauge/whoami
    container_name: api
    restart: unless-stopped
